### PR TITLE
Add Thaumcraft, Thaumic Horizons, Automagy, and Thaumcraft-NEI Plugin

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Does this have the thaumcraft automation stuff or is that a separate addon

**Comment by ike709** [comment]
Thaumcraft is lame.

**Comment by ninjanomnom** [comment]
Did you test this at all, there are no config files here

**Comment by ghost** [comment]
It loads. Also, are config files needed if I don't change the defaults?

**Comment by ninjanomnom** [comment]
Yes you should include them in the pr

**Comment by ghost** [comment]
Configs added

**Pull request merged**
